import { MigrationInterface, QueryRunner } from 'typeorm';

const LEGADO = 'legado_20260916';
const TABELAS_ATUAIS = ['corretores', 'tipos_imovel', 'finalidades_imovel', 'caracteristicas', 'imoveis', 'imoveis_caracteristicas', 'imoveis_midias', 'clientes', 'sessoes_login', 'partes_locacao', 'contrato', 'comissoes', 'parcelas_comissao', 'pastas_drive'];
const auditoria = `criado_em timestamptz NOT NULL DEFAULT now(), alterado_em timestamptz NOT NULL DEFAULT now(),
  criado_por integer NULL REFERENCES corretores(id) ON DELETE RESTRICT, alterado_por integer NULL REFERENCES corretores(id) ON DELETE RESTRICT`;
const COPIA_AUDITORIA = 'criado_em, alterado_em, criado_por, alterado_por';
/** Traduz um UUID do modelo anterior para o inteiro novo pelo mapa temporário. */
const novo = (coluna: string) => `(SELECT m.novo FROM mapa m WHERE m.antigo = ${coluna})`;
const auditoriaMapeada = `criado_em, alterado_em, ${novo('criado_por')}, ${novo('alterado_por')}`;

/**
 * Ids inteiros em todas as tabelas, cadastro único de pessoas (clientes + partes de locação) e ficha do imóvel
 * ampliada. O modelo anterior fica arquivado no schema legado_20260916, sem acesso pela API.
 */
export class IdsInteirosPessoas1789603200000 implements MigrationInterface {
  name = 'IdsInteirosPessoas1789603200000';

  async up(executor: QueryRunner): Promise<void> {
    await executor.query(`LOCK TABLE ${TABELAS_ATUAIS.join(', ')} IN ACCESS EXCLUSIVE MODE`);
    await executor.query(`CREATE SCHEMA ${LEGADO}`);
    for (const tabela of TABELAS_ATUAIS) await executor.query(`ALTER TABLE public.${tabela} SET SCHEMA ${LEGADO}`);
    for (const tipo of ['status_imovel', 'origem_cliente', 'papel_parte_locacao']) await executor.query(`ALTER TYPE public.${tipo} SET SCHEMA ${LEGADO}`);
    await executor.query(`CREATE TYPE status_imovel AS ENUM ('DISPONIVEL','RESERVADO','VENDIDO','ALUGADO','RETIRADO');
      CREATE TYPE origem_pessoa AS ENUM ('SITE','MANUAL');
      CREATE TYPE status_contato AS ENUM ('PENDENTE','RESPONDIDO','FINALIZADO')`);

    // Mapa UUID -> inteiro por tabela, numerando na ordem de criação. Pessoas somam clientes e partes.
    await executor.query('CREATE TEMP TABLE mapa (antigo uuid PRIMARY KEY, novo integer NOT NULL) ON COMMIT DROP');
    for (const tabela of ['corretores', 'tipos_imovel', 'finalidades_imovel', 'caracteristicas', 'imoveis', 'imoveis_midias', 'contrato', 'comissoes', 'parcelas_comissao', 'pastas_drive']) {
      await executor.query(`INSERT INTO mapa (antigo, novo) SELECT id, row_number() OVER (ORDER BY criado_em, id) FROM ${LEGADO}.${tabela}`);
    }
    await executor.query(`INSERT INTO mapa (antigo, novo) SELECT id, row_number() OVER (ORDER BY criado_em, id)
      FROM (SELECT id, criado_em FROM ${LEGADO}.clientes UNION ALL SELECT id, criado_em FROM ${LEGADO}.partes_locacao) AS origem`);

    await executor.query(`CREATE TABLE corretores (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nome text NOT NULL CHECK (char_length(btrim(nome)) BETWEEN 2 AND 100),
      email text NOT NULL UNIQUE CHECK (email = lower(btrim(email))), senha_hash text NOT NULL,
      cpf text NOT NULL CHECK (cpf ~ '^[0-9]{11}$'), whatsapp text NOT NULL, creci text NULL,
      cargo cargo_corretor NOT NULL DEFAULT 'CORRETOR', url_foto text NULL, ativo boolean NOT NULL DEFAULT true, ${auditoria}
    )`);
    await executor.query(`INSERT INTO corretores (id, nome, email, senha_hash, cpf, whatsapp, creci, cargo, url_foto, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('id')}, nome, email, senha_hash, cpf, whatsapp, creci, cargo, url_foto, ativo, ${auditoriaMapeada} FROM ${LEGADO}.corretores`);

    for (const tabela of ['tipos_imovel', 'finalidades_imovel']) {
      await executor.query(`CREATE TABLE ${tabela} (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nome text NOT NULL UNIQUE, slug text NOT NULL UNIQUE, ativo boolean NOT NULL DEFAULT true, ${auditoria})`);
      await executor.query(`INSERT INTO ${tabela} (id, nome, slug, ativo, ${COPIA_AUDITORIA}) SELECT ${novo('id')}, nome, slug, ativo, ${auditoriaMapeada} FROM ${LEGADO}.${tabela}`);
    }
    await executor.query(`CREATE TABLE caracteristicas (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nome text NOT NULL UNIQUE, icone text NULL, ativo boolean NOT NULL DEFAULT true, ${auditoria})`);
    await executor.query(`INSERT INTO caracteristicas (id, nome, icone, ativo, ${COPIA_AUDITORIA}) SELECT ${novo('id')}, nome, icone, ativo, ${auditoriaMapeada} FROM ${LEGADO}.caracteristicas`);

    await executor.query(`CREATE TABLE pessoas (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nome text NOT NULL CHECK (char_length(btrim(nome)) BETWEEN 2 AND 200),
      telefone text NULL, email text NULL, tipo_pessoa tipo_pessoa NULL, cpf_cnpj text NULL, data_nascimento date NULL, endereco text NULL,
      banco_nome text NULL, banco_agencia text NULL, banco_conta text NULL, chave_pix text NULL, observacoes text NULL, mensagem text NULL,
      imovel_id integer NULL, corretor_id integer NOT NULL REFERENCES corretores(id) ON DELETE RESTRICT,
      origem origem_pessoa NOT NULL DEFAULT 'MANUAL', status_contato status_contato NOT NULL DEFAULT 'PENDENTE',
      consentimento boolean NOT NULL DEFAULT false, consentimento_ip text NULL, consentimento_em timestamptz NULL, versao_termos text NULL,
      ativo boolean NOT NULL DEFAULT true, ${auditoria},
      CONSTRAINT consentimento_site CHECK (origem <> 'SITE' OR (consentimento AND consentimento_em IS NOT NULL)),
      CONSTRAINT documento_coerente CHECK (cpf_cnpj IS NULL OR (tipo_pessoa = 'PF' AND cpf_cnpj ~ '^[0-9]{11}$') OR (tipo_pessoa = 'PJ' AND cpf_cnpj ~ '^[0-9]{14}$'))
    )`);

    await executor.query(`CREATE TABLE imoveis (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, titulo text NOT NULL CHECK (char_length(btrim(titulo)) BETWEEN 3 AND 200), slug text NOT NULL UNIQUE,
      tipo_id integer NOT NULL REFERENCES tipos_imovel(id) ON DELETE RESTRICT, finalidade_id integer NOT NULL REFERENCES finalidades_imovel(id) ON DELETE RESTRICT,
      valor_venda numeric(12,2) NULL, valor_locacao numeric(12,2) NULL, valor_condominio numeric(10,2) NULL, valor_iptu numeric(10,2) NULL,
      area_util numeric(10,2) NOT NULL, area_total numeric(10,2) NOT NULL,
      cep text NULL, logradouro text NOT NULL, numero text NOT NULL, complemento text NULL, bairro text NOT NULL, cidade text NOT NULL,
      estado text NOT NULL CHECK (estado ~ '^[A-Z]{2}$'), descricao text NOT NULL CHECK (char_length(descricao) <= 20000),
      status status_imovel NOT NULL DEFAULT 'DISPONIVEL', destaque boolean NOT NULL DEFAULT false,
      corretor_id integer NOT NULL REFERENCES corretores(id) ON DELETE RESTRICT, ativo boolean NOT NULL DEFAULT true,
      proprietario_id integer NULL REFERENCES pessoas(id) ON DELETE RESTRICT, exclusividade boolean NOT NULL DEFAULT false, exclusividade_ate date NULL,
      data_captacao date NULL, chaves text NULL, matricula text NULL, inscricao_municipal text NULL, observacoes_internas text NULL, motivo_baixa text NULL,
      ${auditoria},
      CONSTRAINT chk_imoveis_areas CHECK (area_util > 0 AND area_total >= area_util),
      CONSTRAINT chk_imoveis_valores CHECK ((valor_venda IS NULL OR valor_venda >= 0) AND (valor_locacao IS NULL OR valor_locacao >= 0) AND (valor_condominio IS NULL OR valor_condominio >= 0) AND (valor_iptu IS NULL OR valor_iptu >= 0))
    )`);
    await executor.query(`ALTER TABLE pessoas ADD CONSTRAINT pessoas_imovel_id_fkey FOREIGN KEY (imovel_id) REFERENCES imoveis(id) ON DELETE SET NULL`);
    // Um único valor vira venda ou locação pela finalidade; CONCLUIDO vira VENDIDO ou ALUGADO; o slug troca o UUID pelo id.
    await executor.query(`INSERT INTO imoveis (id, titulo, slug, tipo_id, finalidade_id, valor_venda, valor_locacao, valor_condominio, valor_iptu, area_util, area_total,
        cep, logradouro, numero, complemento, bairro, cidade, estado, descricao, status, corretor_id, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('i.id')}, i.titulo, regexp_replace(i.slug, '-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', '') || '-' || ${novo('i.id')},
        ${novo('i.tipo_id')}, ${novo('i.finalidade_id')},
        CASE WHEN f.slug LIKE '%venda%' THEN i.valor END, CASE WHEN f.slug LIKE '%loca%' THEN i.valor END, i.valor_condominio, i.valor_iptu, i.area_util, i.area_total,
        i.cep, i.logradouro, i.numero, i.complemento, i.bairro, i.cidade, i.estado, i.descricao,
        (CASE i.status::text WHEN 'CONCLUIDO' THEN (CASE WHEN f.slug LIKE '%venda%' AND f.slug NOT LIKE '%loca%' THEN 'VENDIDO' ELSE 'ALUGADO' END) ELSE i.status::text END)::status_imovel,
        ${novo('i.corretor_id')}, i.ativo, i.criado_em, i.alterado_em, ${novo('i.criado_por')}, ${novo('i.alterado_por')}
      FROM ${LEGADO}.imoveis i JOIN ${LEGADO}.finalidades_imovel f ON f.id = i.finalidade_id`);

    await executor.query(`CREATE TABLE imoveis_caracteristicas (
      imovel_id integer NOT NULL REFERENCES imoveis(id) ON DELETE CASCADE, caracteristica_id integer NOT NULL REFERENCES caracteristicas(id) ON DELETE RESTRICT,
      valor text NULL, ativo boolean NOT NULL DEFAULT true, ${auditoria}, PRIMARY KEY (imovel_id, caracteristica_id)
    )`);
    await executor.query(`INSERT INTO imoveis_caracteristicas (imovel_id, caracteristica_id, valor, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('imovel_id')}, ${novo('caracteristica_id')}, valor, ativo, ${auditoriaMapeada} FROM ${LEGADO}.imoveis_caracteristicas`);

    await executor.query(`CREATE TABLE imoveis_midias (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, imovel_id integer NOT NULL REFERENCES imoveis(id) ON DELETE CASCADE,
      tipo tipo_midia NOT NULL, url text NOT NULL, chave_armazenamento text NULL, ordem integer NOT NULL DEFAULT 0,
      capa boolean NOT NULL DEFAULT false, ${auditoria},
      CONSTRAINT chk_imoveis_midias_capa CHECK (NOT capa OR tipo = 'IMAGEM'), CONSTRAINT chk_imoveis_midias_ordem CHECK (ordem >= 0)
    )`);
    await executor.query('ALTER TABLE imoveis_midias ALTER COLUMN criado_por SET NOT NULL');
    await executor.query(`INSERT INTO imoveis_midias (id, imovel_id, tipo, url, chave_armazenamento, ordem, capa, ${COPIA_AUDITORIA})
      SELECT ${novo('id')}, ${novo('imovel_id')}, tipo, url, chave_armazenamento, ordem, capa, ${auditoriaMapeada} FROM ${LEGADO}.imoveis_midias`);

    await executor.query(`INSERT INTO pessoas (id, nome, telefone, email, mensagem, imovel_id, corretor_id, origem, status_contato, consentimento, consentimento_ip, consentimento_em, versao_termos, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('id')}, nome, telefone, email, mensagem, ${novo('imovel_id')}, ${novo('corretor_id')}, origem::text::origem_pessoa,
        (CASE WHEN origem::text = 'SITE' THEN 'PENDENTE' ELSE 'RESPONDIDO' END)::status_contato, consentimento, consentimento_ip, consentimento_em, versao_termos, ativo, ${auditoriaMapeada}
      FROM ${LEGADO}.clientes`);
    // Partes de locação não tinham responsável: herdam o intermediador do primeiro contrato ou o primeiro ADMIN ativo.
    await executor.query(`INSERT INTO pessoas (id, nome, telefone, email, tipo_pessoa, cpf_cnpj, data_nascimento, endereco, banco_nome, banco_agencia, banco_conta, chave_pix, observacoes,
        corretor_id, origem, status_contato, consentimento, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('p.id')}, p.nome, p.telefone, p.email, p.tipo_pessoa, p.cpf_cnpj, p.data_nascimento, p.endereco, p.banco_nome, p.banco_agencia, p.banco_conta, p.chave_pix, p.observacoes,
        COALESCE((SELECT ${novo('c.corretor_id')} FROM ${LEGADO}.contrato c WHERE c.locador_id = p.id OR c.locatario_id = p.id ORDER BY c.criado_em LIMIT 1),
                 (SELECT id FROM corretores WHERE ativo AND cargo = 'ADMIN' ORDER BY id LIMIT 1), (SELECT id FROM corretores ORDER BY id LIMIT 1)),
        'MANUAL', 'FINALIZADO', false, p.ativo, p.criado_em, p.alterado_em, ${novo('p.criado_por')}, ${novo('p.alterado_por')}
      FROM ${LEGADO}.partes_locacao p`);

    await executor.query(`CREATE TABLE sessoes_login (
      token_hash text PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'), corretor_id integer NOT NULL REFERENCES corretores(id) ON DELETE CASCADE,
      expira_em timestamptz NOT NULL, ${auditoria}
    )`);
    await executor.query(`INSERT INTO sessoes_login (token_hash, corretor_id, expira_em, ${COPIA_AUDITORIA})
      SELECT token_hash, ${novo('corretor_id')}, expira_em, ${auditoriaMapeada} FROM ${LEGADO}.sessoes_login WHERE expira_em > now()`);

    await executor.query(`CREATE TABLE contrato (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, numero_contrato text NOT NULL UNIQUE,
      imovel_id integer NOT NULL REFERENCES imoveis(id) ON DELETE RESTRICT, locador_id integer NOT NULL REFERENCES pessoas(id) ON DELETE RESTRICT,
      locatario_id integer NOT NULL REFERENCES pessoas(id) ON DELETE RESTRICT, corretor_id integer NOT NULL REFERENCES corretores(id) ON DELETE RESTRICT,
      data_inicio date NOT NULL, data_fim date NOT NULL CHECK (data_fim >= data_inicio), valor_aluguel numeric(12,2) NOT NULL CHECK (valor_aluguel > 0),
      dia_vencimento integer NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 31), taxa_administracao numeric(5,2) NOT NULL CHECK (taxa_administracao BETWEEN 0 AND 100),
      garantia_locaticia text NOT NULL, indice_reajuste text NOT NULL, cobranca_iptu_condominio text NOT NULL, url_pasta_drive text NULL,
      status status_contrato NOT NULL DEFAULT 'ATIVO', observacoes text NULL, ativo boolean NOT NULL DEFAULT true,
      status_pasta_drive text NOT NULL DEFAULT 'PENDENTE' CHECK (status_pasta_drive IN ('PENDENTE','CRIADA','FALHOU')), ${auditoria},
      CONSTRAINT partes_distintas CHECK (locador_id <> locatario_id), CONSTRAINT contrato_arquivado CHECK (ativo OR status = 'INATIVO')
    )`);
    await executor.query(`INSERT INTO contrato (id, numero_contrato, imovel_id, locador_id, locatario_id, corretor_id, data_inicio, data_fim, valor_aluguel, dia_vencimento, taxa_administracao,
        garantia_locaticia, indice_reajuste, cobranca_iptu_condominio, url_pasta_drive, status, observacoes, ativo, status_pasta_drive, ${COPIA_AUDITORIA})
      SELECT ${novo('id')}, numero_contrato, ${novo('imovel_id')}, ${novo('locador_id')}, ${novo('locatario_id')}, ${novo('corretor_id')}, data_inicio, data_fim, valor_aluguel, dia_vencimento, taxa_administracao,
        garantia_locaticia, indice_reajuste, cobranca_iptu_condominio, url_pasta_drive, status, observacoes, ativo, status_pasta_drive, ${auditoriaMapeada} FROM ${LEGADO}.contrato`);

    await executor.query(`CREATE TABLE comissoes (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, tipo_operacao tipo_operacao_comissao NOT NULL,
      contrato_id integer NULL REFERENCES contrato(id) ON DELETE RESTRICT, imovel_id integer NOT NULL REFERENCES imoveis(id) ON DELETE RESTRICT,
      pessoa_id integer NOT NULL REFERENCES pessoas(id) ON DELETE RESTRICT, valor_total numeric(12,2) NOT NULL CHECK (valor_total > 0),
      quantidade_parcelas integer NOT NULL CHECK (quantidade_parcelas BETWEEN 1 AND 600), observacoes text NULL,
      ativo boolean NOT NULL DEFAULT true, ${auditoria},
      CONSTRAINT comissao_operacao_contrato CHECK ((tipo_operacao = 'LOCACAO' AND contrato_id IS NOT NULL) OR (tipo_operacao = 'VENDA' AND contrato_id IS NULL))
    )`);
    await executor.query(`INSERT INTO comissoes (id, tipo_operacao, contrato_id, imovel_id, pessoa_id, valor_total, quantidade_parcelas, observacoes, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('id')}, tipo_operacao, ${novo('contrato_id')}, ${novo('imovel_id')}, ${novo('cliente_id')}, valor_total, quantidade_parcelas, observacoes, ativo, ${auditoriaMapeada} FROM ${LEGADO}.comissoes`);

    await executor.query(`CREATE TABLE parcelas_comissao (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, comissao_id integer NOT NULL REFERENCES comissoes(id) ON DELETE CASCADE,
      numero_parcela integer NOT NULL CHECK (numero_parcela >= 1), data_vencimento date NOT NULL, valor numeric(12,2) NOT NULL CHECK (valor > 0),
      status status_parcela_comissao NOT NULL DEFAULT 'PENDENTE', pago_em timestamptz NULL, observacao_pagamento text NULL,
      ativo boolean NOT NULL DEFAULT true, ${auditoria}, UNIQUE (comissao_id, numero_parcela),
      CONSTRAINT parcela_pagamento CHECK ((status = 'PAGO' AND pago_em IS NOT NULL) OR (status <> 'PAGO' AND pago_em IS NULL))
    )`);
    await executor.query(`INSERT INTO parcelas_comissao (id, comissao_id, numero_parcela, data_vencimento, valor, status, pago_em, observacao_pagamento, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('id')}, ${novo('comissao_id')}, numero_parcela, data_vencimento, valor, status, pago_em, observacao_pagamento, ativo, ${auditoriaMapeada} FROM ${LEGADO}.parcelas_comissao`);

    await executor.query(`CREATE TABLE pastas_drive (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, chave text NOT NULL UNIQUE, id_drive text NOT NULL UNIQUE,
      pasta_pai_id text NOT NULL, nome text NOT NULL, ativo boolean NOT NULL DEFAULT true, ${auditoria}
    )`);
    // A chave de pasta de contrato carregava o UUID do contrato; passa a carregar o id inteiro.
    await executor.query(`INSERT INTO pastas_drive (id, chave, id_drive, pasta_pai_id, nome, ativo, ${COPIA_AUDITORIA})
      SELECT ${novo('id')},
        CASE WHEN chave LIKE 'contrato:%' THEN COALESCE('contrato:' || (SELECT m.novo FROM mapa m WHERE m.antigo::text = substr(chave, 10)), chave) ELSE chave END,
        id_drive, pasta_pai_id, nome, ativo, ${auditoriaMapeada} FROM ${LEGADO}.pastas_drive`);

    for (const tabela of ['corretores', 'tipos_imovel', 'finalidades_imovel', 'caracteristicas', 'pessoas', 'imoveis', 'imoveis_midias', 'contrato', 'comissoes', 'parcelas_comissao', 'pastas_drive']) {
      await executor.query(`SELECT setval(pg_get_serial_sequence('${tabela}', 'id'), COALESCE((SELECT max(id) FROM ${tabela}), 0) + 1, false)`);
    }

    await executor.query('CREATE EXTENSION IF NOT EXISTS pg_trgm');
    for (const [tabela, coluna] of [['corretores', 'nome'], ['imoveis', 'titulo'], ['imoveis', 'cidade'], ['imoveis', 'bairro'], ['pessoas', 'nome'], ['pessoas', 'telefone'], ['pessoas', 'cpf_cnpj']]) {
      await executor.query(`CREATE INDEX busca_${tabela}_${coluna} ON ${tabela} USING gin (${coluna} gin_trgm_ops)`);
    }
    const indices: Array<[string, string, string]> = [
      ['idx_imoveis_publico', 'imoveis', 'ativo, status, criado_em'], ['idx_imoveis_corretor', 'imoveis', 'corretor_id'], ['idx_imoveis_proprietario', 'imoveis', 'proprietario_id'],
      ['idx_imoveis_classificacao', 'imoveis', 'tipo_id, finalidade_id'], ['idx_imoveis_midias_ordem', 'imoveis_midias', 'imovel_id, ordem'],
      ['idx_pessoas_corretor', 'pessoas', 'corretor_id, criado_em, id'], ['idx_pessoas_imovel', 'pessoas', 'imovel_id'], ['idx_pessoas_status', 'pessoas', 'status_contato'],
      ['idx_sessoes_login_expira_em', 'sessoes_login', 'expira_em'], ['idx_sessoes_login_corretor', 'sessoes_login', 'corretor_id'],
      ['idx_contrato_locador', 'contrato', 'locador_id, status'], ['idx_contrato_locatario', 'contrato', 'locatario_id, status'], ['idx_contrato_corretor', 'contrato', 'corretor_id'], ['idx_contrato_vencimento', 'contrato', 'status, data_fim'],
      ['idx_comissoes_contrato', 'comissoes', 'contrato_id'], ['idx_comissoes_imovel', 'comissoes', 'imovel_id'], ['idx_comissoes_pessoa', 'comissoes', 'pessoa_id'], ['idx_parcelas_comissao_status', 'parcelas_comissao', 'status, data_vencimento'],
    ];
    for (const [nome, tabela, colunas] of indices) await executor.query(`CREATE INDEX ${nome} ON ${tabela} (${colunas})`);
    await executor.query('CREATE UNIQUE INDEX uq_imoveis_midias_capa ON imoveis_midias (imovel_id) WHERE capa = true');
    await executor.query("CREATE UNIQUE INDEX unico_contrato_ativo_imovel ON contrato (imovel_id) WHERE status = 'ATIVO'");
    await executor.query(`REVOKE ALL ON SCHEMA ${LEGADO} FROM PUBLIC`);
  }

  down(): Promise<void> {
    return Promise.reject(new Error('Reversão automática recusada: restaure backup verificado em ambiente isolado e faça corte coordenado; dados novos não podem ser apagados.'));
  }
}
