import { MigrationInterface, QueryRunner } from 'typeorm';

const auditoria = `criado_em timestamptz NOT NULL DEFAULT now(), alterado_em timestamptz NOT NULL DEFAULT now(),
  criado_por integer NULL REFERENCES corretores(id) ON DELETE RESTRICT, alterado_por integer NULL REFERENCES corretores(id) ON DELETE RESTRICT`;

/**
 * Comissão editável com plano versionado e histórico imutável; índices de reajuste e tipos de contrato com snapshot
 * no contrato. Não recalcula parcelas nem pagamentos: tudo o que existe vira a versão 1.
 */
export class ComissaoVersionadaCadastrosContrato1789689600000 implements MigrationInterface {
  name = 'ComissaoVersionadaCadastrosContrato1789689600000';

  async up(executor: QueryRunner): Promise<void> {
    await executor.query('LOCK TABLE contrato, comissoes, parcelas_comissao IN ACCESS EXCLUSIVE MODE');

    await executor.query(`ALTER TABLE comissoes
      ADD COLUMN versao_plano integer NOT NULL DEFAULT 1 CHECK (versao_plano >= 1),
      ADD COLUMN versao_registro integer NOT NULL DEFAULT 1 CHECK (versao_registro >= 1)`);
    await executor.query('ALTER TABLE parcelas_comissao ADD COLUMN versao_plano integer NOT NULL DEFAULT 1 CHECK (versao_plano >= 1)');
    // O nome da unicidade antiga foi gerado pelo PostgreSQL; localiza pela definição em vez de supor o nome.
    const antigas = await executor.query(`SELECT c.conname FROM pg_constraint c
      WHERE c.conrelid = 'parcelas_comissao'::regclass AND c.contype = 'u'
        AND (SELECT array_agg(a.attname::text ORDER BY a.attname) FROM pg_attribute a WHERE a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)) = ARRAY['comissao_id', 'numero_parcela']`) as Array<{ conname: string }>;
    if (antigas.length !== 1) throw new Error('Migração interrompida: unicidade de parcelas por comissão e número não encontrada.');
    await executor.query(`ALTER TABLE parcelas_comissao DROP CONSTRAINT "${antigas[0].conname}"`);
    await executor.query('ALTER TABLE parcelas_comissao ADD CONSTRAINT parcelas_comissao_plano_numero UNIQUE (comissao_id, versao_plano, numero_parcela)');

    await executor.query(`CREATE TABLE comissao_revisoes (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, comissao_id integer NOT NULL REFERENCES comissoes(id) ON DELETE RESTRICT,
      versao_plano integer NOT NULL CHECK (versao_plano >= 1), tipo_operacao tipo_operacao_comissao NOT NULL,
      contrato_id integer NULL REFERENCES contrato(id) ON DELETE RESTRICT, imovel_id integer NOT NULL REFERENCES imoveis(id) ON DELETE RESTRICT,
      pessoa_id integer NOT NULL REFERENCES pessoas(id) ON DELETE RESTRICT, valor_total numeric(12,2) NOT NULL CHECK (valor_total > 0),
      quantidade_parcelas integer NOT NULL CHECK (quantidade_parcelas BETWEEN 1 AND 600), primeiro_vencimento date NOT NULL,
      autor_id integer NULL REFERENCES corretores(id) ON DELETE RESTRICT,
      origem text NOT NULL CHECK (origem IN ('CRIACAO','EDICAO','MIGRACAO')), criado_em timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT comissao_revisoes_plano UNIQUE (comissao_id, versao_plano)
    )`);
    await executor.query(`CREATE FUNCTION comissao_revisoes_imutavel() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN RAISE EXCEPTION 'Revisões de comissão são imutáveis.'; END $$`);
    await executor.query(`CREATE TRIGGER comissao_revisoes_imutavel BEFORE UPDATE OR DELETE ON comissao_revisoes
      FOR EACH ROW EXECUTE FUNCTION comissao_revisoes_imutavel()`);
    await executor.query(`INSERT INTO comissao_revisoes (comissao_id, versao_plano, tipo_operacao, contrato_id, imovel_id, pessoa_id, valor_total, quantidade_parcelas, primeiro_vencimento, autor_id, origem, criado_em)
      SELECT c.id, 1, c.tipo_operacao, c.contrato_id, c.imovel_id, c.pessoa_id, c.valor_total, c.quantidade_parcelas,
        COALESCE((SELECT min(p.data_vencimento) FROM parcelas_comissao p WHERE p.comissao_id = c.id), (c.criado_em AT TIME ZONE 'America/Cuiaba')::date),
        NULL, 'MIGRACAO', c.criado_em
      FROM comissoes c ORDER BY c.id`);

    await executor.query(`CREATE TABLE indices_reajuste (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nome text NOT NULL CHECK (char_length(btrim(nome)) BETWEEN 2 AND 100),
      nome_normalizado text NOT NULL UNIQUE, periodicidade_meses integer NOT NULL CHECK (periodicidade_meses BETWEEN 1 AND 600),
      regra text NULL CHECK (regra IS NULL OR char_length(regra) <= 2000), ativo boolean NOT NULL DEFAULT true, ${auditoria}
    )`);
    await executor.query(`CREATE TABLE tipos_contrato (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, nome text NOT NULL CHECK (char_length(btrim(nome)) BETWEEN 2 AND 100),
      nome_normalizado text NOT NULL UNIQUE, descricao text NULL CHECK (descricao IS NULL OR char_length(descricao) <= 1000),
      ativo boolean NOT NULL DEFAULT true, ${auditoria}
    )`);

    // Contratos existentes ficam sem referência; o texto livre de reajuste permanece até a classificação.
    await executor.query(`ALTER TABLE contrato
      ADD COLUMN tipo_contrato_id integer NULL REFERENCES tipos_contrato(id) ON DELETE RESTRICT,
      ADD COLUMN tipo_contrato_nome text NULL,
      ADD COLUMN indice_reajuste_id integer NULL REFERENCES indices_reajuste(id) ON DELETE RESTRICT,
      ADD COLUMN indice_reajuste_nome text NULL,
      ADD COLUMN indice_reajuste_periodicidade_meses integer NULL,
      ADD COLUMN indice_reajuste_regra text NULL,
      ADD CONSTRAINT contrato_snapshot_tipo CHECK ((tipo_contrato_id IS NULL) = (tipo_contrato_nome IS NULL)),
      ADD CONSTRAINT contrato_snapshot_indice CHECK ((indice_reajuste_id IS NULL) = (indice_reajuste_nome IS NULL) AND (indice_reajuste_id IS NULL) = (indice_reajuste_periodicidade_meses IS NULL))`);

    // parcelas_comissao já é indexada por (comissao_id, versao_plano) através da nova unicidade.
    await executor.query('CREATE INDEX idx_contrato_tipo ON contrato (tipo_contrato_id)');
    await executor.query('CREATE INDEX idx_contrato_indice ON contrato (indice_reajuste_id)');
  }

  down(): Promise<void> {
    return Promise.reject(new Error('Reversão automática recusada: restaure backup verificado em ambiente isolado; o histórico de revisões e os planos substituídos não podem ser apagados.'));
  }
}
