import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { Lease } from '../rentals/lease.entity';
import { CommissionDto, MarkCommissionPaidDto } from './finance.dto';
import { AcquisitionCommission, CommissionInstallment, CommissionInstallmentStatus, commissionResponse } from './commission.entity';

function cents(value: string): bigint { if (!/^\d{1,10}\.\d{2}$/.test(value) || /^0\.00$/.test(value)) throw new BadRequestException('O aluguel do contrato deve ser positivo.'); return BigInt(value.replace('.', '')); }
function civil(value: string): Date { const d = new Date(`${value}T00:00:00Z`); if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || d.toISOString().slice(0, 10) !== value) throw new BadRequestException('Data de vencimento inválida.'); return d; }
function addMonths(date: Date, months: number): string { const d = new Date(date); d.setUTCMonth(d.getUTCMonth() + months); return d.toISOString().slice(0, 10); }
@Injectable()
export class FinanceService {
  constructor(@InjectRepository(AcquisitionCommission) private readonly commissions: Repository<AcquisitionCommission>, @InjectRepository(Lease) private readonly leases: Repository<Lease>, private readonly database: DataSource) {}
  async get(leaseId: string) { const found = await this.commissions.findOne({ where: { leaseId }, relations: { installments: true } }); if (!found) throw new NotFoundException('Comissão não cadastrada para este contrato.'); return commissionResponse(found); }
  async create(dto: CommissionDto) { civil(dto.firstDueDate); return this.database.transaction(async manager => { const leases = manager.getRepository(Lease); const lease = await leases.findOne({ where: { id: dto.leaseId }, lock: { mode: 'pessimistic_read' } }); if (!lease) throw new NotFoundException('Contrato não encontrado.'); if (lease.status === 'ENDED') throw new BadRequestException('Contrato encerrado não pode receber nova comissão.'); const repo = manager.getRepository(AcquisitionCommission); if (await repo.existsBy({ leaseId: dto.leaseId })) throw new ConflictException('Este contrato já possui comissão cadastrada.'); const total = cents(lease.rentAmount); const base = total / BigInt(dto.installmentCount); const remainder = total % BigInt(dto.installmentCount); const commission = repo.create({ leaseId: lease.id, lease, totalAmount: lease.rentAmount, installmentCount: dto.installmentCount, notes: dto.notes, installments: [] }); commission.installments = Array.from({ length: dto.installmentCount }, (_, index) => { const amount = base + (BigInt(index) < remainder ? 1n : 0n); return Object.assign(new CommissionInstallment(), { installmentNumber: index + 1, dueDate: addMonths(civil(dto.firstDueDate), index), amount: `${amount / 100n}.${(amount % 100n).toString().padStart(2, '0')}`, status: CommissionInstallmentStatus.PENDING, paidAt: null, paymentNote: null, commission }); }); return commissionResponse(await repo.save(commission)); }); }
  async markPaid(id: string, dto: MarkCommissionPaidDto) { const installment = await this.database.getRepository(CommissionInstallment).findOne({ where: { id }, relations: { commission: true } }); if (!installment) throw new NotFoundException('Parcela não encontrada.'); if (installment.status === CommissionInstallmentStatus.PAID) throw new ConflictException('Esta parcela já foi confirmada.'); installment.status = CommissionInstallmentStatus.PAID; installment.paidAt = new Date(); installment.paymentNote = dto.paymentNote; await this.database.getRepository(CommissionInstallment).save(installment); return this.get(installment.commission.leaseId); }
}
